### PR TITLE
Change gitlab force_remove_source_branch to bool

### PR DESCRIPTION
**Pull request by jezhodges**
Gitlab merge requests currently give an error message:
`json: cannot unmarshal bool into Go struct field .object_attributes.merge_params.force_remove_source_branch of type string`

Gitlab appear to have changed `force_remove_source_branch` to a boolean in the API. This PR updates those structs.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
We should instead remove `MergeParams` from the structure since it is not being used.  The reason is that merging this change would fix Drone for the latest version of GitLab, but would also break Drone for anyone not using the latest version of GitLab.

**Comment by jezhodges** [comment]
@bradrydzewski Good point. I've updated the structs to ignore MergeParams

**Comment by jezhodges** [comment]
Any movement with this @bradrydzewski? As it's blocking a few of my pipeline jobs...

**Comment by jezhodges** [comment]
@bradrydzewski any update on getting this merged?

**Pull request merged**
