### PR TITLE
Added `CompareChanges` function to `GitService`.

### PR DESCRIPTION
**Pull request by chhsia0**
CompareChanges returns the changeset between two commits. If the source commit is not an ancestor of the target commit, it is up to the driver to return a 2-way or 3-way diff changeset.

### CODE REVIEW

**Comment by chhsia0** [comment]
@bradrydzewski Would you mind taking a look at this PR? Thanks :)

**Comment by bradrydzewski** [comment]
@chhsia0 thanks!  I really appreciate that you included extensive testing and support for as many providers as possible :)

**Comment by tboerger** [comment]
As Gitea supports a diff view between branches I'm pretty sure there must also be an API for it. @lunny or @appleboy, maybe somebody of you could jump in with a followup pr?

**Comment by lunny** [comment]
@tboerger will try this.

**Comment by lunny** [comment]
I think we have an issue for that and need a PR. https://github.com/go-gitea/gitea/issues/5561

**Pull request merged**
