### PR TITLE
Fix gitea tag link

### PR DESCRIPTION
**Pull request by lunny**
As title.

### CODE REVIEW

**Comment by lunny** [comment]
I think since 1.3.0, see https://github.com/go-gitea/gitea/commit/513375c429435ba60a667b219bdfb00e5b760b38

**Comment by tboerger** [comment]
But gitea had some fallback mechanism if this part have not been added to the URL? Because this had been working so far.

**Comment by jolheiser** [comment]
It looks like there was a redirect for "legacy" repositories in that commit, perhaps that worked for a while?  
The code for redirecting "legacy" is still in `master`, but it has changed a little.

**Comment by lunny** [comment]
So it's now broken. See https://drone.gitea.com/gitea/go-sdk/254 .

**Comment by tboerger** [comment]
> So it's now broken. See https://drone.gitea.com/gitea/go-sdk/254 .

I can't see where something should be broken...

**Comment by lunny** [comment]
click the link on `v0.11.0`, you will get 404.

图片

**Comment by tboerger** [comment]
You are right, I haven't realized that before. @bradrydzewski that fix should get into another release of Drone to fix the tag links for the Gitea integration.

**Pull request merged**
